// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTab(arg1:string,arg2:string,arg3:string):Promise<main.PanelTab>;

export function ApplyPanelIcon(arg1:string):Promise<main.PanelIconApplyResult>;

export function ApplyWindowTheme(arg1:string):Promise<void>;

export function CleanOrphanProfiles():Promise<number>;

export function CreatePanel(arg1:string,arg2:string,arg3:boolean):Promise<main.PanelConfig>;

export function CreatePanelShortcut(arg1:string):Promise<main.PanelShortcutResult>;

export function DeletePanel(arg1:string,arg2:boolean):Promise<void>;

export function DeleteTab(arg1:string,arg2:string):Promise<void>;

export function ExportConfig():Promise<boolean>;

export function GetPanelTabs(arg1:string):Promise<Array<main.PanelTab>>;

export function GetSettings():Promise<main.AppSettings>;

export function ImportConfig():Promise<boolean>;

export function InspectPanelIcon(arg1:string):Promise<main.PanelIconPreview>;

export function InspectPanelShortcut(arg1:string):Promise<main.PanelShortcutPreview>;

export function ListOrphanProfiles():Promise<Array<string>>;

export function ListPanelShortcuts(arg1:string):Promise<Array<string>>;

export function ListPanels():Promise<Array<main.PanelConfig>>;

export function OpenPanel(arg1:string):Promise<void>;

export function PinPanelToTaskbar(arg1:string):Promise<main.PinTaskbarResult>;

export function Quit():Promise<void>;

export function ResetPanelData(arg1:string):Promise<void>;

export function RevealPanelShortcut(arg1:string):Promise<void>;

export function SetActiveTab(arg1:string,arg2:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetLightweightQuitOnLastPanel(arg1:boolean):Promise<void>;

export function SetPanelAlwaysOnTop(arg1:string,arg2:boolean):Promise<void>;

export function SetPanelCloseAction(arg1:string):Promise<void>;

export function SetPanelPasswordAutosave(arg1:string,arg2:string):Promise<void>;

export function SetPanelSessionMode(arg1:string,arg2:string):Promise<void>;

export function SetShowTrayIcon(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function ShowMainWindow():Promise<void>;

export function UpdatePanel(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.PanelConfig>;

export function UpdatePanelTabs(arg1:string,arg2:Array<main.PanelTab>):Promise<void>;
