// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTab'](arg1, arg2, arg3);
}

export function ApplyPanelIcon(arg1) {
  return window['go']['main']['App']['ApplyPanelIcon'](arg1);
}

export function ApplyWindowTheme(arg1) {
  return window['go']['main']['App']['ApplyWindowTheme'](arg1);
}

export function CleanOrphanProfiles() {
  return window['go']['main']['App']['CleanOrphanProfiles']();
}

export function CreatePanel(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePanel'](arg1, arg2, arg3);
}

export function CreatePanelShortcut(arg1) {
  return window['go']['main']['App']['CreatePanelShortcut'](arg1);
}

export function DeletePanel(arg1, arg2) {
  return window['go']['main']['App']['DeletePanel'](arg1, arg2);
}

export function DeleteTab(arg1, arg2) {
  return window['go']['main']['App']['DeleteTab'](arg1, arg2);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function GetPanelTabs(arg1) {
  return window['go']['main']['App']['GetPanelTabs'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function InspectPanelIcon(arg1) {
  return window['go']['main']['App']['InspectPanelIcon'](arg1);
}

export function InspectPanelShortcut(arg1) {
  return window['go']['main']['App']['InspectPanelShortcut'](arg1);
}

export function ListOrphanProfiles() {
  return window['go']['main']['App']['ListOrphanProfiles']();
}

export function ListPanelShortcuts(arg1) {
  return window['go']['main']['App']['ListPanelShortcuts'](arg1);
}

export function ListPanels() {
  return window['go']['main']['App']['ListPanels']();
}

export function OpenPanel(arg1) {
  return window['go']['main']['App']['OpenPanel'](arg1);
}

export function PinPanelToTaskbar(arg1) {
  return window['go']['main']['App']['PinPanelToTaskbar'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResetPanelData(arg1) {
  return window['go']['main']['App']['ResetPanelData'](arg1);
}

export function RevealPanelShortcut(arg1) {
  return window['go']['main']['App']['RevealPanelShortcut'](arg1);
}

export function SetActiveTab(arg1, arg2) {
  return window['go']['main']['App']['SetActiveTab'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetLightweightQuitOnLastPanel(arg1) {
  return window['go']['main']['App']['SetLightweightQuitOnLastPanel'](arg1);
}

export function SetPanelAlwaysOnTop(arg1, arg2) {
  return window['go']['main']['App']['SetPanelAlwaysOnTop'](arg1, arg2);
}

export function SetPanelCloseAction(arg1) {
  return window['go']['main']['App']['SetPanelCloseAction'](arg1);
}

export function SetPanelPasswordAutosave(arg1, arg2) {
  return window['go']['main']['App']['SetPanelPasswordAutosave'](arg1, arg2);
}

export function SetPanelSessionMode(arg1, arg2) {
  return window['go']['main']['App']['SetPanelSessionMode'](arg1, arg2);
}

export function SetShowTrayIcon(arg1) {
  return window['go']['main']['App']['SetShowTrayIcon'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function UpdatePanel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePanel'](arg1, arg2, arg3, arg4);
}

export function UpdatePanelTabs(arg1, arg2) {
  return window['go']['main']['App']['UpdatePanelTabs'](arg1, arg2);
}
